version: '3'
services:
  pryocdn_website:
    container_name: node-autodeploy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    ports:
      - 4000:4000
    stdin_open: true
    tty: true